### ISSUE TITLE
Node Classification

### ISSUE THREAD

**Issue by Wienhannover** [Graph-COM/GSAT#13]
Hi, thanks for organizing the code so neatly, I am wondering if the code applicable for node classification task. If yes, can you please point out which part should be changed?

**Comment by siqim** [comment]
Hi! In our paper and implementation, we do not evaluate our method on node-level tasks, but it should be easy to transfer GSAT to node-level tasks. A typical way to apply perturbation-based methods on node-level tasks is to utilize local computation graphs. Take a look at Algorithm 1 from Appendix A of [PGExplainer](https://arxiv.org/pdf/2011.04573.pdf), where a detailed description is provided.

Thank you for your interest in our work. Let me know if you have any other questions.
