### ISSUE TITLE
Unstable accuracy on test set

### ISSUE THREAD

**Issue by simoons95** [Graph-COM/GSAT#6]
Hello,

I also have a second question (see https://github.com/Graph-COM/GSAT/issues/5 for the first one).
When I run your code on ba_2motifs, I obtain the following graph: 
![image](https://user-images.githubusercontent.com/22727700/202241253-ed6410de-6bc3-4cc1-933f-28b8bd72e2f2.png)
Fortunately, the validation set have the exact same behaviour as the test set, so when the validation set accuracy is high, the test set accuracy is high too, hence the good results.
Is it expected that it is so unstable? What could I do to avoid that?

**Comment by siqim** [comment]
Thanks for reporting this issue! After fixing issue #5 by PR #7, I just tested the code, and now it should be a lot more stable.

**Comment by siqim** [comment]
With #7/#8, learning edge attention for undirected graphs should be much more stable, and I will be closing this issue now. Thanks again for pointing out this issue, and feel free to let us know if you have any further questions!
